version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
      target: dev
    volumes:
      - ./server:/carlos/src/app
      - /carlos/src/app/node_modules/
    command: npm run start:debug
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: DfPA4s&2@4GQ@iY#bQet
      PORT: 4000
    ports:
      - 4000:4000
      - 9229:9229
  
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: dev
    command: npm run start
    volumes:
      - ./frontend:/carlos/frontend/src/app
      - /carlos/frontend/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - api

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432

#   postgres_admin:
#     image: dpage/pgadmin4:4.28
#     depends_on: 
#       - postgres
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: password
#     ports:
#       - 5050:80